"""Regenerate supabase/migrations/001_init.sql from the ORM models in app/db.py."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app.db import Base  # noqa: E402
from app.services.storage import BUCKETS  # noqa: E402

d = postgresql.dialect()
out = [
    "-- VoiceCircle schema for Supabase Postgres (generated by api/scripts/gen_migration.py from app/db.py).",
    "-- The API also creates missing tables on startup (init_db); RLS and buckets are only set up here.",
    '-- Run in the Supabase SQL editor or: psql "$DATABASE_URL" -f 001_init.sql',
    "",
]
for t in Base.metadata.sorted_tables:
    out.append(str(CreateTable(t, if_not_exists=True).compile(dialect=d)).strip() + ";\n")
    out += [str(CreateIndex(ix, if_not_exists=True).compile(dialect=d)).strip() + ";" for ix in t.indexes]
    out.append("")
out.append("-- Row Level Security: the FastAPI backend connects as the database owner and enforces circle")
out.append("-- membership itself (app/deps.py). RLS with no policies blocks direct access with the anon key.")
out += [f"ALTER TABLE {t.name} ENABLE ROW LEVEL SECURITY;" for t in Base.metadata.sorted_tables]
vals = ",\n  ".join(f"('{b}', '{b}', false)" for b in BUCKETS)
out.append(f"\n-- Private storage buckets for voice samples, uploaded recordings and generated audio\n"
           f"INSERT INTO storage.buckets (id, name, public) VALUES\n  {vals}\nON CONFLICT (id) DO NOTHING;\n")
dest = ROOT.parent / "supabase" / "migrations" / "001_init.sql"
dest.write_text("\n".join(out))
print(f"wrote {dest}")
